### ISSUE TITLE
Contribute icon upstream?

### ISSUE THREAD

**Issue by wincent** [DinkDonk/kitty-icon#2]
Absolutely gorgeous icon, @DinkDonk. 😍 

Don't know how open @kovidgoyal would be to accepting a contribution upstream, but have you considered sharing this with him?

**Comment by andreypopp** [comment]
https://github.com/kovidgoyal/kitty/issues/3310

But the icon is really good looking

**Comment by MindTooth** [comment]
It’s really a nice one. 👍🏻

Not sure that it follows the [HIG](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) on macOS.  One could solve this by supplying a custom icon for just macOS though.

**Comment by wincent** [comment]
> kovidgoyal/kitty#3310

Ah, that looks pretty conclusive then. Thanks @andreypopp!

**Comment by DinkDonk** [comment]
Thank you @wincent !
I'm very hesitant to create a pull request on design stuff – it's a subjective matter and even though Kitty is pretty new, it still has well known preexisting branding.

I was unaware of the issue @andreypopp mentioned, but that further seals the deal.
The best thing is probably to just let the alternative icons live outside of the main distribution/repo.

@MindTooth  – my icon follows the latest MacOS App Icon guidelines, even though they are just guidelines and not rules.
Breaking the rounded rectangle is allowed but should be done subtly as I feel like I have managed:

> If you must alter the shape, prefer subtle adjustments that continue to express a rounded rectangle silhouette.
> – _Human Interface Guidelines_
