### ISSUE TITLE
URL Failure When Dragging kitty-dark.icns Over Preview

### ISSUE THREAD

**Issue by appcabinet** [DinkDonk/kitty-icon#4]
I am receiving a failure when trying to load the icns icon over the preview.

```
Open URL Error

Unknown URL type, cannot open:
  file:///Users/marcelo.mantilla/Programming/personal-configurations/kitty-dark.icns

Press Enter or Esc to exit
```

**Comment by farkmarnum** [comment]
@marcelo-mantilla make sure you're dragging it over the top left icon not the big one:

<img width="377" alt="Screen Shot 2022-07-01 at 10 17 57 AM" src="https://user-images.githubusercontent.com/46835237/176912368-bf30a4ca-1c74-41e5-80c9-63204a34502d.png">

**Comment by hoclun-rigsep** [comment]
I did the same thing; this should perhaps be promoted to the README.

**Comment by linux-root** [comment]
Got the same Issue. Thanks @marcelo-mantilla for opening this issue

**Comment by DinkDonk** [comment]
> I did the same thing; this should perhaps be promoted to the README.

I'm happy to merge pull requests
