### ISSUE TITLE
Provide SVG

### ISSUE THREAD

**Issue by bennypowers** [DinkDonk/kitty-icon#7]
Cute icon, thanks for publishing. Please add an SVG to the repo. Thank you!

**Comment by johannesrave** [comment]
also love the icon, would like to use it on ubuntu - could you provide an svg?

**Comment by DinkDonk** [comment]
The source material uses features that are not compatible with the SVG spec, and would result in a big part being converted to bitmaps. I suggest wrapping the PNG in an SVG – It would serve the same purpose.
I'm happy to merge pull requests if someone reworks the gradients and shadows in the Affinity Designer source file to be compatible with SVG.
